name: TCGMCAU
version: ${project.version}-${build.number}
description: |
    ${project.description}
    Built ${git.build.time} from git revision ${git.commit.id.abbrev}
    <${git.commit.user.name}> ${git.commit.message.short}

author: Ullarah
authors: [TerrorBite]

main: com.ullarah.tcgmcau.mInit

depend: [WorldEdit, WorldGuard]

commands:
  cards:
    description: Allows you to view instructions and register for cards.
    usage: |
      <command> : View instructions for cards.
      <command> give : Gives a card to a player.
      <command> purge : Purge a players stash.

permissions:
  cards.default:
    description: Sets single and total cards for newbies. Settings in config.yml
  cards.plus:
    description: Sets single and total cards for plus users. Settings in config.yml
  cards.donator:
    description: Sets single and total cards for donators. Settings in config.yml
  cards.dplus:
    description: Sets single and total cards for donator plus users. Settings in config.yml
  cards.staff:
    description: Sets single and total cards for staff users. Settings in config.yml
  cards.staff.commands:
    description: Grant all of the staff commands
    children:
      cards.staff.check: true
      cards.staff.give: true
      cards.staff.give.random: true
      cards.staff.info: true
      cards.staff.list: true
      cards.staff.maintenance: true
      cards.staff.purge: true
      cards.staff.reload: true

